Build package before publishing
lowes/product-viewer pull request #42
Opened 2022-01-27 20:18 UTC by john-lowes

We need to build the project before publishing it so that the JavaScript (`dist/` and `lib/` folders) are included

2022-01-27 21:47 UTC, braustin20 requested changes

2022-01-27 21:47 UTC, braustin20 commented on .github/workflows/lerna.yml
> +          npm run build
I agree with your comment, we should run this in product-viewer specifically. Can you change this to:
```
- name: Build packages
  working-directory: ./packages/product-viewer
  run: |
    npm run build
```

2022-01-27 21:47 UTC, braustin20 commented on .github/workflows/lerna.yml
> +          npm run build
I've never used `working-directory` before so we should test this

2022-01-28 00:43 UTC, john-lowes commented on .github/workflows/lerna.yml
> +          npm run build
Nice, looks like that worked! 
https://github.com/lowes/product-viewer/runs/4974624088

2022-01-28 00:58 UTC, braustin20 commented on .github/workflows/lerna.yml
> +          npm run build
Oh awesome

2022-01-28 00:58 UTC, braustin20 approved these changes

2022-01-28 23:53 UTC, jayzeng approved these changes

2022-01-29 00:01 UTC, merged